### ISSUE TITLE
`set-output` command is deprecated and will be disabled soon warning in client workflows

### ISSUE THREAD

**Issue by dsaltares** [amondnet/vercel-action#185]
<img width="1544" alt="image" src="https://user-images.githubusercontent.com/570314/195356867-714fcf97-e176-41eb-aeaf-c2e96bdfcf86.png">

Github announced this deprecation here https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/. They say `@actions/core@1.10.0` and higher solve the issue, however, this action is using v1.2.6
https://github.com/amondnet/vercel-action/blob/master/package.json#L26.

**Comment by dmarcucci** [comment]
Also worth pointing out that there are a couple of example workflows in this repo that use the command. However, it should be pretty easy to fix those by following the info / example in the blog post.

**Comment by michalak111** [comment]
this should be resolved by https://github.com/amondnet/vercel-action/pull/189 @amondnet would you mind releasing changes?

**Comment by dmarcucci** [comment]
> this should be resolved by #189 @amondnet would you mind releasing changes?

This fixes the example workflows that I mentioned, but does not fix the actual usages of the command in the action itself. As such, this is still an issue.

**Comment by michalak111** [comment]
Yes you are right `@actions/core` needs to be updated as well, missed that
